# Generated by Django 6.0.3 on 2026-05-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='observacion',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='direccion',
            field=models.CharField(choices=[('Mucho Lote', 'Mucho Lote'), ('Bastión Popular', 'Bastión Popular'), ('Mapasingue', 'Mapasingue'), ('Flor de Bastión', 'Flor de Bastión'), ('Monte Sinaí', 'Monte Sinaí'), ('Guasmo', 'Guasmo'), ('Prosperina', 'Prosperina'), ('Los Ceibos', 'Los Ceibos'), ('Urdesa', 'Urdesa'), ('Kennedy', 'Kennedy'), ('Otra', 'Otra dirección')], default='Mucho Lote', max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='curso',
            field=models.CharField(choices=[('Inicial', [('Inicial 1', 'Inicial 1'), ('Inicial 2', 'Inicial 2')]), ('Básica', [('1ro Básica', '1ro Básica'), ('2do Básica', '2do Básica'), ('3ro Básica', '3ro Básica'), ('4to Básica', '4to Básica'), ('5to Básica', '5to Básica'), ('6to Básica', '6to Básica'), ('7mo Básica', '7mo Básica')]), ('Media', [('8vo Básica', '8vo Básica'), ('9no Básica', '9no Básica'), ('10mo Básica', '10mo Básica')]), ('Bachillerato', [('1ro Bachillerato', '1ro Bachillerato'), ('2do Bachillerato', '2do Bachillerato'), ('3ro Bachillerato', '3ro Bachillerato')])], max_length=50),
        ),
    ]
