# Generated by Django 6.0.5 on 2026-05-28 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_estudiante_observacion_estudiante_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_intento', models.CharField(blank=True, help_text='Correo que se intento usar', max_length=254)),
                ('accion', models.CharField(choices=[('login_exitoso', 'Login Exitoso'), ('login_fallido', 'Login Fallido'), ('logout', 'Cierre de Sesion')], max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('navegador', models.CharField(blank=True, max_length=300)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria de Login',
                'verbose_name_plural': 'Auditorias de Login',
                'ordering': ['-fecha'],
            },
        ),
    ]
